In [1]:
'''
Implement logistic regression and test it using any dataset of your choice from UCI repository.
The output should include Confusion Matrix, Accuracy, Error rate, Precision, Recall and F-Measure.
'''

''

In [7]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [43]:
df = pd.read_csv('titanic.csv')
df = df.dropna()

In [44]:
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [14]:
X_encoder = LabelEncoder()
df[['Sex']] = X_encoder.fit_transform(df[['Sex']])

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [15]:
X = df[['Pclass','Sex','Age','Siblings/Spouses Aboard','Parents/Children Aboard','Fare']].to_numpy()
Y = df[['Survived']].to_numpy()

In [16]:

X_scaler = StandardScaler()

X_scaled = X_scaler.fit_transform(X)
X_scaled[0]

array([ 0.83052363,  0.74026551, -0.52936601,  0.42990395, -0.4749808 ,
       -0.50358635])

In [18]:
from sklearn.linear_model import LogisticRegression

In [28]:
model = LogisticRegression()
X_train,X_test,Y_train,Y_test = train_test_split(X_scaled,Y,test_size=0.2,shuffle=True,random_state=2)

In [29]:
model.fit(X_train,Y_train)
preds = model.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [30]:
print("Accuracy:",accuracy_score(Y_test,preds))

Accuracy: 0.7808988764044944


In [31]:
print("Precision:",precision_score(Y_test,preds))

Precision: 0.7162162162162162


In [32]:
print("Recall",recall_score(Y_test,preds))

Recall 0.7464788732394366


In [33]:
print("F1-Score",f1_score(Y_test,preds))

F1-Score 0.7310344827586208


In [34]:
print("Confusion Matrix:\n",confusion_matrix(Y_test,preds))

Confusion Matrix:
 [[86 21]
 [18 53]]


In [35]:
print("error rate:",(1-accuracy_score(Y_test,preds)))

error rate: 0.2191011235955056


In [41]:
#Test sample
import numpy as np
test = [1,'female',38.0,1,0,71.28]
test_encoded = test[:]
test_encoded[1] = X_encoder.transform(['female'])
test_scaled = X_scaler.transform(np.array(test_encoded).reshape(1,-1))
test_scaled

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([[-1.56127657, -1.35086667,  0.60426454,  0.42990395, -0.4749808 ,
         0.78334612]])

In [42]:
print("Prediction of ",test," is: ",model.predict(test_scaled)[0])

Prediction of  [1, 'female', 38.0, 1, 0, 71.28]  is:  1
